name: Run PHPUnit tests

on:
  workflow_call:
    inputs:
      php-version:
        description: PHP versions used
        required: false
        default: "8.4"
        type: string
      runs-on:
        description: The "runs-on" platform config
        required: false
        default: 'ubuntu-latest'
        type: string
      php-extensions:
        description: PHP extensions to install
        required: false
        default: "mbstring, intl, pdo_mysql"
        type: string
      coverage-report:
        description: Generate coverage report and upload to Codecov
        required: false
        default: false
        type: boolean
      codecov-token:
        description: Codecov token
        required: false
        default: ${{ secrets.CODECOV_TOKEN }}
        type: string

jobs:
  phpunit:
    name: PHP ${{ inputs.php-version }}
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          coverage: pcov
          ini-values: memory_limit=-1

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit \
            --testdox \
            --log-junit junit.xml \
            --coverage-text \
            --coverage-clover coverage.xml 

      - name: Upload test results to Codecov
        if: ${{ inputs.coverage-report }}
        uses: codecov/test-results-action@v1
        with:
          file: junit.xml
          token: ${{ inputs.codecov-token }}

      - name: Upload coverage to Codecov
        if: ${{ inputs.coverage-report }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ inputs.codecov-token }}