name: Run PHPUnit tests

on:
  workflow_call:
    inputs:
      php-version:
        description: PHP versions used
        required: false
        default: "8.4"
        type: string
      runs-on:
        description: The "runs-on" platform config
        required: false
        default: 'ubuntu-latest'
        type: string
      php-extensions:
        description: PHP extensions to install
        required: false
        default: "mbstring, intl, pdo_mysql"
        type: string
      coverage-report:
        description: Generate coverage report and upload to Codecov
        required: false
        default: false
        type: boolean
      mysql-db:
        description: MySQL database name
        required: false
        default: "app"
        type: string
      mysql-user:
        description: MySQL user name
        required: false
        default: "app"
        type: string
      mysql-password:
        description: MySQL user password
        required: false
        default: "!ChangeMe!"
        type: string

jobs:
  phpunit:
    name: PHP ${{ inputs.php-version }}
    runs-on: ${{ inputs.runs-on }}

    services:
      database:
        image: mysql:8-oracle
        env:
          MYSQL_DATABASE: ${{ inputs.mysql-db }}
          MYSQL_USER: ${{ inputs.mysql-user }}
          MYSQL_PASSWORD: ${{ inputs.mysql-password }}
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          coverage: pcov
          ini-values: memory_limit=-1

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --no-progress --no-interaction

      - name: Run PHPUnit
        run: |
          vendor/bin/phpunit \
            --testdox \
            --log-junit junit.xml \
            --coverage-text \
            --coverage-clover coverage.xml 

      - name: Upload test results to Codecov
        if: ${{ inputs.coverage-report }}
        uses: codecov/test-results-action@v1
        with:
          file: junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        if: ${{ inputs.coverage-report }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}